# Generated by Django 4.1.5 on 2023-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeattendancemodel',
            name='time_of_attendance',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
