# Generated by Django 4.1.5 on 2023-02-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeattendancecreationmodel',
            name='location_point_range',
            field=models.FloatField(default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='location_point_range',
            field=models.FloatField(default=100.0, null=True),
        ),
    ]
