# Generated by Django 4.1.5 on 2023-03-16 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 17, 20, 36, 887254, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 17, 20, 36, 882277, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
