# Generated by Django 4.1.5 on 2023-02-21 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_alter_officeattendancecreationmodel_location_point_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeattendancecreationmodel',
            name='attendance_duration',
            field=models.DurationField(default=datetime.timedelta(days=1), null=True),
        ),
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DurationField(default=datetime.timedelta(days=1), null=True),
        ),
    ]
