# Generated by Django 4.1.5 on 2023-02-07 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_alter_officeattendancemodel_time_of_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeattendancemodel',
            name='time_of_attendance',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studentattendancemodel',
            name='time_of_attendance',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
