# Generated by Django 4.1.5 on 2023-03-17 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_alter_officeattendancecreationmodel_attendance_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 21, 20, 41, 615333, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 21, 20, 41, 583179, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
