# Generated by Django 4.1.5 on 2023-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_alter_officeattendancecreationmodel_attendance_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeattendancecreationmodel',
            name='AttendanceTitle',
        ),
        migrations.RemoveField(
            model_name='studentattendancecreationmodel',
            name='AttendanceTitle',
        ),
        migrations.AlterField(
            model_name='studentattendancetakingmodel',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='officeattendancecreationmodel',
            name='attendanceTitle',
            field=models.CharField(default='Title', max_length=120),
        ),
        migrations.AddField(
            model_name='studentattendancecreationmodel',
            name='attendanceTitle',
            field=models.CharField(default='Title', max_length=120),
        ),
    ]
