# Generated by Django 4.1.5 on 2023-02-23 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_remove_officeattendancecreationmodel_attendancetitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
