# Generated by Django 4.1.5 on 2023-02-23 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_alter_studentattendancecreationmodel_attendance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DurationField(default=datetime.timedelta(days=1), null=True),
        ),
    ]
