# Generated by Django 4.1.5 on 2023-02-24 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0006_alter_studentattendancecreationmodel_attendance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 19, 23, 27, 580899, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
