# Generated by Django 4.1.5 on 2023-02-24 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0007_alter_studentattendancecreationmodel_attendance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 21, 25, 24, 927248, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
