# Generated by Django 4.1.5 on 2023-03-21 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0007_alter_officeattendancecreationmodel_attendance_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 12, 48, 37, 68785, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 12, 48, 37, 60791, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
