# Generated by Django 4.1.5 on 2023-02-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0008_alter_studentattendancecreationmodel_attendance_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendancecreationmodel',
            name='attendance_duration',
            field=models.DateTimeField(default='2023-02-25T21:31:22.685153+00:00', null=True),
        ),
    ]
