# Generated by Django 4.1.5 on 2023-03-21 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_email_confirmation_token_user_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_token',
            field=models.URLField(default=uuid.uuid4, editable=False),
        ),
    ]
