# Generated by Django 4.1.5 on 2023-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_email_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(default='d006b370c81811edbde518cf5eb070a6', editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
