# Generated by Django 4.1.5 on 2023-03-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_email_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(default='bdbe7e3ec81a11ed841718cf5eb070a6', editable=False, max_length=36),
        ),
    ]
